version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    command: sh -c "echo 'Admin running at http://localhost:8080' && nginx -g 'daemon off;'"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    command: sh -c "echo 'Client running at http://localhost:8081' && nginx -g 'daemon off;'"
