version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
