template: |-
  <div class="box">
    <div>
      <img 
        :src="imageUrl" 
        :alt="title"
      >
    </div>
    <div class="box-content">
      <h2 class="box-title">
        {{ title }}
      </h2>

      <div class="box-text">
        {{ text }} 
      </div>
      <div class="buttons">
        <button @click="handleClick">
          Buttons 
        </button>
      </div>
    </div>
     
  </div>
styles: |-
  .box {
      position: relative;
      margin: 0 auto;
      width: 280px;
      height: 320px;
      border: 1px solid #00000022;
      border-radius: 8px;
      overflow: hidden;
  }

  img {
      width: 100%;
      height: auto;
      object-fit: cover;
  }

  .box-content {
      padding: 10px;
  }

  .box-title {
     font-weight: 600;
  }

  .box-text {
      margin-top: 10px;
      font-weight: 600;
      font-size: 12px;
  }

  .buttons {
      position: absolute;
      bottom: 10px;
  }

  .buttons button {
      background: #7748f8;
      color: #fff;
      border-radius: 4px;
      padding: 12px;
      border: none;
      outline: none;
      font-weight: 600;
      font-size: 12px;
  }
